suppressPackageStartupMessages({library(data.table);library(jsonlite);library(digest)})
source('utils/public_data.R');source('utils/exports.R')
main <- function() {
 root <- tempfile('site-workflow-test-');dir.create(root);on.exit(unlink(root,recursive=TRUE),add=TRUE)
 # Minimal site configuration gets the same standard settings as the full runner.
 config_path <- file.path(root,'config.json')
 write_json(list(site_name='SYNTHETIC',tables_path=root,file_type='parquet'),config_path,auto_unbox=TRUE)
 previous <- Sys.getenv('CLIF_CONFIG_PATH',unset=NA_character_)
 on.exit(if(is.na(previous))Sys.unsetenv('CLIF_CONFIG_PATH') else Sys.setenv(CLIF_CONFIG_PATH=previous),add=TRUE)
 Sys.setenv(CLIF_CONFIG_PATH=config_path)
 source('utils/config.R',local=TRUE)
 stopifnot(config$site_timezone=='America/Chicago',config$mwas_exposure_cache=='data/public/exposures',
           config$mwas_acs_dir=='data/public/acs/2017',identical(config$derive_sofa,FALSE))
 write_json(list(site_name='SYNTHETIC',tables_path=root,file_type='parquet',site_timezone='America/New_York'),config_path,auto_unbox=TRUE)
 stopifnot(load_config(config_path)$site_timezone=='America/New_York')
 # Curated export must exclude nearby private files and reject identifiers in an allowlisted CSV.
 run <- file.path(root,'run');dir.create(file.path(run,'federated'),recursive=TRUE);dir.create(file.path(run,'private'))
 writeLines('DO NOT EXPORT',file.path(run,'private','cohort.rds'))
 for(name in c('site_estimates.csv','shared_exposure_estimates.csv'))fwrite(data.table(site='SYNTHETIC',log_or=.1,se=.2),file.path(run,'federated',name))
 write_json(list(version='synthetic'),file.path(run,'federated','protocol.json'))
 fwrite(data.table(characteristic='Admissions',n=100),file.path(run,'federated','table1.csv'))
 writeLines('<html>Synthetic aggregates</html>',file.path(run,'federated','report.html'))
 out <- file.path(root,'export');mwas_prepare_exports(run,out)
 stopifnot(nrow(fread(file.path(out,'privacy_audit.csv')))==0,!any(grepl('private|cohort.rds',list.files(out,recursive=TRUE))))
 manifest <- read_json(file.path(out,'export_manifest.json'))
 for(name in names(manifest$files_sha256))stopifnot(mwas_sha256(file.path(out,name))==manifest$files_sha256[[name]])
 fwrite(data.table(patient_id='synthetic_patient'),file.path(run,'federated','site_estimates.csv'))
 bad <- try(mwas_prepare_exports(run,file.path(root,'bad_export')),silent=TRUE)
 stopifnot(inherits(bad,'try-error'),!dir.exists(file.path(root,'bad_export')))
 # Public-data corruption is detected, without any network request.
 ex <- file.path(root,'public');dir.create(file.path(ex,'pm25'),recursive=TRUE)
 file <- file.path(ex,'pm25','pm25_2020_01.parquet');writeLines('fixture',file)
 rec <- list(product='pm25',year=2020L,month=1L,path='pm25/pm25_2020_01.parquet',sha256=mwas_sha256(file))
 write_json(list(scope='national_public_no_clinical_filter',files=list(rec)),file.path(ex,'manifest.json'),auto_unbox=TRUE)
 writeLines('corrupt',file)
 bad <- try(mwas_validate_public_data(ex,root,2020L,2020L),silent=TRUE)
 stopifnot(inherits(bad,'try-error'),grepl('Missing/corrupt',as.character(bad),fixed=TRUE))
 cat('Site workflow checks passed: allowlisted exports, identifier rejection, checksums and corruption detection.\n')
}
main()
